version: '3.8'

services:
  # O serviço de cliente RLFE será replicado conforme NUM_CLIENTS
  client:
    build: .
    environment:
      - NUM_CLIENTS=${NUM_CLIENTS}
    volumes:
      - ./client/reports:/app/client/reports
      - ./client/results:/app/client/results
      - ./DatasetIOT:/app/DatasetIOT:ro
    entrypoint: ["python", "client.py"]
    # Os argumentos são definidos dinamicamente abaixo
    command: ["--cid", "${CID}", "--num_clients", "${NUM_CLIENTS}", "--num_total_clients", "${NUM_TOTAL_CLIENTS}"]

# Geração automática dos serviços cliente
# Para usar, criar um ficheiro .env com NUM_CLIENTS=N
# E executar: docker-compose up --scale client=N
