version: '3.8'

services:
  # Servidor Flower para coordenar a aprendizagem federada
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - flower-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9091"]
      interval: 5s
      timeout: 5s
      retries: 5

  # O serviço de cliente RLFE será replicado conforme NUM_CLIENTS
  client:
    build: .
    environment:
      - NUM_CLIENTS=${NUM_CLIENTS}
      - SERVER_ADDRESS=server:9091
    volumes:
      - ./client/reports:/app/client/reports
      - ./client/results:/app/client/results
      - ./DatasetIOT:/app/DatasetIOT:ro
    entrypoint: ["python", "client.py"]
    # Os argumentos são definidos dinamicamente abaixo
    command: ["--cid", "${CID}", "--num_clients", "${NUM_CLIENTS}", "--num_total_clients", "${NUM_TOTAL_CLIENTS}", "--server_address", "server:9091"]
    networks:
      - flower-net
    depends_on:
      server:
        condition: service_healthy

# Definição da rede para comunicação entre servidor e clientes
networks:
  flower-net:
    driver: bridge

# Geração automática dos serviços cliente
# Para usar, criar um ficheiro .env com NUM_CLIENTS=N
# E executar: docker-compose up --scale client=N
