
services:
  # Servidor Flower para coordenar a aprendizagem federada na abordagem RLFE
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "/app/server.py"]
    ports:
      - "9091:9091"
    networks:
      - flower-net
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9091"]
      interval: 5s
      timeout: 5s
      retries: 5

  client_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_1
    volumes:
      - ./client/reports:/app/client/reports
      - ./client/results:/app/client/results
      - ./DatasetIOT:/app/DatasetIOT:ro
    working_dir: /app/client
    command: ["python", "client.py", "--cid", "1", "--num_clients", "3", "--num_total_clients", "6", "--server_address", "server:9091"]
    networks:
      - flower-net
    depends_on:
      server:
        condition: service_healthy

  client_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_2
    volumes:
      - ./client/reports:/app/client/reports
      - ./client/results:/app/client/results
      - ./DatasetIOT:/app/DatasetIOT:ro
    working_dir: /app/client
    command: ["python", "client.py", "--cid", "2", "--num_clients", "3", "--num_total_clients", "6", "--server_address", "server:9091"]
    networks:
      - flower-net
    depends_on:
      server:
        condition: service_healthy

  client_3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_3
    volumes:
      - ./client/reports:/app/client/reports
      - ./client/results:/app/client/results
      - ./DatasetIOT:/app/DatasetIOT:ro
    working_dir: /app/client
    command: ["python", "client.py", "--cid", "3", "--num_clients", "3", "--num_total_clients", "6", "--server_address", "server:9091"]
    networks:
      - flower-net
    depends_on:
      server:
        condition: service_healthy

networks:
  flower-net:
    driver: bridge
